site_name: Curso HCI
site_url: https://labnanocell.github.io/curso-hci/

theme:
  name: material
  logo: assets/img/nanocell-logo.png
  favicon: assets/img/favicon.ico
  language: pt
  features:
    - navigation.prune
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/ui.js

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: pt
          name: Português
          default: true
          build: true
          nav:
            - Início: index.md
            - Onboarding e Higiene Científica:
                - Visão geral: 00-onboarding/index.md
                - Introdução ao HCI/HCA: 00-onboarding/intro/index.md
                - Pergunta científica e operacionalização: 00-onboarding/pergunta/index.md
                - Desenho experimental I: 00-onboarding/desenho-experimental/index.md
                - Desenho Experimental II: 00-onboarding/batch-effects/index.md
                - Git básico para pós-graduação: 00-onboarding/git/index.md
            - Glossário: 90-glossario/index.md

        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Onboarding and Scientific Workflow Hygiene:
                - Overview: 00-onboarding/index.md
                - Introduction to HCI/HCA: 00-onboarding/intro/index.md
                - Scientific question and operationalization: 00-onboarding/scientific-question/index.md
                - Experimental design I: 00-onboarding/experimental-design/index.md
                - Experimental design II: 00-onboarding/batch-effects/index.md
                - Basic Git for graduate students: 00-onboarding/git/index.md
            - Glossary: 90-glossary/index.md
